//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatterBox.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Like
    {
        public int LikesID { get; set; }
        public string UserFollow { get; set; }
        public string UserLikes { get; set; }
    }
}
